export const DEFAULT_PREFIX = {
  title: "Hi 👋, I'm",
  currentWork: '🔭 I’m currently working on',
  currentLearn: '🌱 I’m currently learning',
  collaborateOn: '👯 I’m looking to collaborate on',
  helpWith: '🤝 I’m looking for help with',
  ama: '💬 Ask me about',
  contact: '📫 How to reach me',
  resume: '📄 Know about my experiences',
  funFact: '⚡ Fun fact',
  portfolio: '👨‍💻 All of my projects are available at',
  blog: '📝 I regularly write articles on',
};

export const DEFAULT_DATA = {
  title: '',
  subtitle: 'A passionate frontend developer from India',
  profileimg:'https://camo.githubusercontent.com/2ff23fb270a58ba226e90e723853d8d033a8dae68bcefab0145082170dcbde88/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f76322f726573697a653a6669743a313336302f312a6e57515f55354e4b45664e6547435466685f322d4d772e676966',
  currentWork: '',
  currentLearn: '',
  collaborateOn: '',
  helpWith: '',
  ama: '',
  contact: '',
  funFact: '',
  twitterBadge: false,
  visitorsBadge: false,
  badgeStyle: 'flat',
  badgeColor: '0e75b6',
  badgeLabel: 'Profile views',
  githubProfileTrophy: false,
  githubStats: false,
  githubStatsOptions: {
    theme: '',
    titleColor: '',
    textColor: '',
    bgColor: '',
    hideBorder: false,
    cacheSeconds: null,
    locale: 'en',
  },
  topLanguages: false,
  topLanguagesOptions: {
    theme: '',
    titleColor: '',
    textColor: '',
    bgColor: '',
    hideBorder: false,
    cacheSeconds: null,
    locale: 'en',
  },
  streakStats: false,
  streakStatsOptions: {
    theme: '',
  },
  devDynamicBlogs: false,
  mediumDynamicBlogs: false,
  rssDynamicBlogs: false,
};

export const DEFAULT_LINK = {
  currentWork: '',
  collaborateOn: '',
  helpWith: '',
  portfolio: '',
  blog: '',
  resume: '',
};

export const DEFAULT_SOCIAL = {
  github: '',
  dev: '',
  linkedin: '',
  codepen: '',
  stackoverflow: '',
  kaggle: '',
  codesandbox: '',
  fb: '',
  instagram: '',
  twitter: '',
  dribbble: '',
  behance: '',
  medium: '',
  youtube: '',
  codechef: '',
  hackerrank: '',
  codeforces: '',
  leetcode: '',
  topcoder: '',
  hackerearth: '',
  geeks_for_geeks: '',
  discord: '',
  rssurl: '',
};

export const DEFAULT_SUPPORT = {
  buyMeACoffee: '',
};
