export const DEFAULT_PREFIX = {
  title: "Hi 👋, I'm",
  currentWork: "🔭&nbsp;&nbsp; I’m currently working on",
  currentLearn: "🌱&nbsp;&nbsp; I’m currently learning",
  collaborateOn: "👯&nbsp;&nbsp; I’m looking to collaborate on",
  helpWith: "🤝&nbsp;&nbsp; I’m looking for help with",
  ama: "💬&nbsp;&nbsp; Ask me about",
  contact: "📫&nbsp;&nbsp; How to reach me",
  resume: "📄&nbsp;&nbsp; Know about my experiences",
  funFact: "⚡&nbsp;&nbsp; Fun fact",
  portfolio: "👨‍💻&nbsp;&nbsp; All of my projects are available at",
  blog: "📝&nbsp;&nbsp; I regularly write articles on",
}

export const DEFAULT_DATA = {
  title: "",
  subtitle: "A passionate frontend developer from India",
  currentWork: "",
  currentLearn: "",
  collaborateOn: "",
  helpWith: "",
  ama: "",
  contact: "",
  funFact: "",
  twitterBadge: false,
  visitorsBadge: false,
  badgeStyle: "flat",
  badgeColor: "0e75b6",
  badgeLabel: "Profile views",
  githubProfileTrophy: false,
  githubStats: false,
  githubStatsOptions: {
    theme: "",
    titleColor: "",
    textColor: "",
    bgColor: "",
    hideBorder: false,
    cacheSeconds: null,
    locale: "en",
  },
  topLanguages: false,
  topLanguagesOptions: {
    theme: "",
    titleColor: "",
    textColor: "",
    bgColor: "",
    hideBorder: false,
    cacheSeconds: null,
    locale: "en",
  },
  streakStats: false,
  streakStatsOptions: {
    theme: "",
  },
  devDynamicBlogs: false,
  mediumDynamicBlogs: false,
  rssDynamicBlogs: false,
}

export const DEFAULT_LINK = {
  currentWork: "",
  collaborateOn: "",
  helpWith: "",
  portfolio: "",
  blog: "",
  resume: "",
}

export const DEFAULT_SOCIAL = {
  github: "",
  dev: "",
  linkedin: "",
  codepen: "",
  stackoverflow: "",
  kaggle: "",
  codesandbox: "",
  fb: "",
  instagram: "",
  twitter: "",
  dribbble: "",
  behance: "",
  medium: "",
  youtube: "",
  codechef: "",
  hackerrank: "",
  codeforces: "",
  leetcode: "",
  topcoder: "",
  hackerearth: "",
  geeks_for_geeks: "",
  discord: "",
  rssurl: "",
}

export const DEFAULT_SUPPORT = {
    buyMeACoffee: ""
}
