//const baseURL = 'https://konpa.github.io/devicon/devicon.git/icons/';
const skills = ['vuejs', 'react', 'angularjs', 'aws', 'android', 'backbonejs',
    'bootstrap', 'c', 'coffeescript',
    'cplusplus', 'css3', 'csharp', 'd3js', 'django', 'docker', 'dotnet', 'electron', 'go',
    'gulp', 'html5', 'java', 'javascript', 'typescript', 'laravel', 'mongodb', 'mysql', 'php', 'postgresql',
    'rails', 'redis', 'redhat', 'ruby', 'rust',
    'sass', 'scala', 'nodejs', 'python', 'swift', 'oracle', 'nginx', 'linux', 'redux',
    'webpack', 'express', 'flutter', 'dart'];
const icons = {
    vuejs: 'https://konpa.github.io/devicon/devicon.git/icons/vuejs/vuejs-original-wordmark.svg',
    react: 'https://konpa.github.io/devicon/devicon.git/icons/react/react-original-wordmark.svg',
    angularjs: 'https://konpa.github.io/devicon/devicon.git/icons/angularjs/angularjs-original.svg',
    aws: 'https://konpa.github.io/devicon/devicon.git/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
    android: 'https://konpa.github.io/devicon/devicon.git/icons/android/android-original-wordmark.svg',
    backbonejs: 'https://konpa.github.io/devicon/devicon.git/icons/backbonejs/backbonejs-original-wordmark.svg',
    bootstrap: 'https://konpa.github.io/devicon/devicon.git/icons/bootstrap/bootstrap-plain.svg',
    c: 'https://konpa.github.io/devicon/devicon.git/icons/c/c-original.svg',
    coffeescript: 'https://konpa.github.io/devicon/devicon.git/icons/coffeescript/coffeescript-original-wordmark.svg',
    cplusplus: 'https://konpa.github.io/devicon/devicon.git/icons/cplusplus/cplusplus-original.svg',
    css3: 'https://konpa.github.io/devicon/devicon.git/icons/css3/css3-original-wordmark.svg',
    csharp: 'https://konpa.github.io/devicon/devicon.git/icons/csharp/csharp-original.svg',
    d3js: 'https://konpa.github.io/devicon/devicon.git/icons/d3js/d3js-original.svg',
    django: 'https://konpa.github.io/devicon/devicon.git/icons/django/django-original.svg',
    docker: 'https://konpa.github.io/devicon/devicon.git/icons/docker/docker-original-wordmark.svg',
    dotnet: 'https://konpa.github.io/devicon/devicon.git/icons/dot-net/dot-net-original-wordmark.svg',
    electron: 'https://konpa.github.io/devicon/devicon.git/icons/electron/electron-original.svg',
    express: 'https://konpa.github.io/devicon/devicon.git/icons/express/express-original-wordmark.svg',
    git: 'https://konpa.github.io/devicon/devicon.git/icons/git/git-original-wordmark.svg',
    go: 'https://konpa.github.io/devicon/devicon.git/icons/go/go-original.svg',
    gulp: 'https://konpa.github.io/devicon/devicon.git/icons/gulp/gulp-plain.svg',
    html5: 'https://konpa.github.io/devicon/devicon.git/icons/html5/html5-original-wordmark.svg',
    illustrator: 'https://konpa.github.io/devicon/devicon.git/icons/illustrator/illustrator-plain.svg',
    java: 'https://konpa.github.io/devicon/devicon.git/icons/java/java-original-wordmark.svg',
    javascript: 'https://konpa.github.io/devicon/devicon.git/icons/javascript/javascript-original.svg',
    laravel: 'https://konpa.github.io/devicon/devicon.git/icons/laravel/laravel-plain-wordmark.svg',
    meteor: 'https://konpa.github.io/devicon/devicon.git/icons/meteor/meteor-original-wordmark.svg',
    mongodb: 'https://konpa.github.io/devicon/devicon.git/icons/mongodb/mongodb-original-wordmark.svg',
    mysql: 'https://konpa.github.io/devicon/devicon.git/icons/mysql/mysql-original-wordmark.svg',
    nginx: 'https://konpa.github.io/devicon/devicon.git/icons/nginx/nginx-original.svg',
    nodejs: 'https://konpa.github.io/devicon/devicon.git/icons/nodejs/nodejs-original-wordmark.svg',
    oracle: 'https://konpa.github.io/devicon/devicon.git/icons/oracle/oracle-original.svg',
    photoshop: 'https://konpa.github.io/devicon/devicon.git/icons/photoshop/photoshop-plain.svg',
    php: 'https://konpa.github.io/devicon/devicon.git/icons/php/php-original.svg',
    postgresql: 'https://konpa.github.io/devicon/devicon.git/icons/postgresql/postgresql-original-wordmark.svg',
    python: 'https://konpa.github.io/devicon/devicon.git/icons/python/python-original-wordmark.svg',
    rails: 'https://konpa.github.io/devicon/devicon.git/icons/rails/rails-original-wordmark.svg',
    redis: 'https://konpa.github.io/devicon/devicon.git/icons/redis/redis-original-wordmark.svg',
    redhat: 'https://konpa.github.io/devicon/devicon.git/icons/redhat/redhat-original-wordmark.svg',
    ruby: 'https://konpa.github.io/devicon/devicon.git/icons/ruby/ruby-original-wordmark.svg',
    rust: 'https://konpa.github.io/devicon/devicon.git/icons/rust/rust-plain.svg',
    sass: 'https://konpa.github.io/devicon/devicon.git/icons/sass/sass-original.svg',
    scala: 'https://konpa.github.io/devicon/devicon.git/icons/scala/scala-original-wordmark.svg',
    sketch: 'https://konpa.github.io/devicon/devicon.git/icons/sketch/sketch-original-wordmark.svg',
    swift: 'https://konpa.github.io/devicon/devicon.git/icons/swift/swift-original-wordmark.svg',
    typescript: 'https://konpa.github.io/devicon/devicon.git/icons/typescript/typescript-original.svg',
    linux: 'https://konpa.github.io/devicon/devicon.git/icons/linux/linux-original.svg',
    redux: 'https://konpa.github.io/devicon/devicon.git/icons/redux/redux-original.svg',
    webpack: 'https://konpa.github.io/devicon/devicon.git/icons/webpack/webpack-original.svg',
    flutter: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/flutter.svg',
    dart: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/dart.svg',
}

const initialSkillState = {}
skills.forEach(skill => {
    initialSkillState[skill] = false
});

export { initialSkillState, icons, skills };